# Generated by Django 4.2.1 on 2023-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_car_loan_status_home_loan_status_userinfo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_loan',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home_loan',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='money',
            field=models.IntegerField(null=True),
        ),
    ]
