# Generated by Django 4.2.1 on 2023-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_loan',
            name='Aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='home_loan',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
