# Generated by Django 4.2.1 on 2023-05-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_home_loan_aadhaar_card_home_loan_pan_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usefull_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
