# Generated by Django 4.2.1 on 2023-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_what_we_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Aadhaar_card',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
